### PR TITLE
Windows autolaunch

### PR DESCRIPTION
**Pull request by jdheeter**
Cross platform compilation is handled correctly now.

### CODE REVIEW

**Comment by nazar-pc** [comment]
Can you squash commits, please? There are multiple that are a part of the same exact thing, it would make history much smaller and cleaner.

**Comment by jdheeter** [comment]
recent commits squashed

**Comment by nazar-pc** [comment]
> recent commits squashed

Well, when you squash commits, the number of commits is supposed to decrease. Here I would expect 2 or maybe 3 commits total. But it only got bigger :disappointed:

**Comment by jdheeter** [comment]
Usually I squash during merge of the PR instead of removing old commits but yes I can make it happen.

**Comment by nazar-pc** [comment]
You have a few distinct changes here, so it makes sense to me to have 2 or 3 commits with independent changes. Instead of squashing everything into one during merge.

**Pull request closed without merging**
