### PR TITLE
Setup eslint

### PR DESCRIPTION
**Pull request by jdheeter**
Added eslint basic config and handled some warnings. Also made some tweaks in SetupPlot component.

### CODE REVIEW

**Comment by nazar-pc** [comment]
This shares all but one commit with `alpha`, did you intend to create a PR against that one instead of `main`?

**Comment by jdheeter** [comment]
closing

**Comment by jdheeter** [comment]
got it 👍

**Review by isSerge — APPROVED** [review]

**Comment by nazar-pc** [comment]
I trust Serge on this one

**Comment by nazar-pc** [comment]
`alpha` PR just got even bigger. It was supposed to be merged only after `alpha` was merged.

**Comment by jdheeter** [comment]
Your comments on alpha are resolved in this branch

**Pull request merged**
